# Generated by Django 4.0.5 on 2022-07-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('late_investigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='number'),
        ),
    ]
