# Generated by Django 4.0.5 on 2022-07-16 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('late_investigation', '0004_customuser_route_delete_userroute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='route',
            new_name='routes',
        ),
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=70)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='late_investigation.route')),
            ],
        ),
    ]
