# Generated by Django 4.0.5 on 2022-07-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('late_investigation', '0005_rename_route_customuser_routes_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delay',
            name='date',
        ),
        migrations.AddField(
            model_name='delay',
            name='day',
            field=models.PositiveSmallIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='delay',
            name='month',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='delay',
            name='year',
            field=models.PositiveSmallIntegerField(default=2022),
        ),
    ]
