# Generated by Django 4.0.5 on 2022-07-17 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('late_investigation', '0007_delay_users_alter_delay_day_alter_delay_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='delay',
            name='users',
        ),
        migrations.AddField(
            model_name='delay',
            name='users',
            field=models.ManyToManyField(through='late_investigation.UserDelay', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdelay',
            name='delay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='late_investigation.delay'),
        ),
        migrations.AddField(
            model_name='userdelay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
